import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import TitleSetter from "@/components/title-setter";
import { AIButton } from "@/components/ai-button";
import { ThemeProvider } from "next-themes";
import { Fab } from "@mui/material";
import Footer from "@/components/footer";
import Shenanigans from "@/components/shenanigans";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <Shenanigans />
          <Navbar />
          <Fab
            variant="extended"
            className="fixed! bottom-3 left-2"
            href="/createticket"
          >
            Submit ticket <AIButton text="with ai" />
          </Fab>
          <AIButton className="fixed! bottom-0 right-0" />
          {children}
          <TitleSetter />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
